# Generated by Django 2.2.7 on 2019-11-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uprofile', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='no-image-user.png', upload_to='avatars'),
        ),
    ]
