# Generated by Django 2.2.7 on 2019-11-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanager', '0001_initial'),
        ('postmanager', '0002_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='categorymanager.Category'),
        ),
    ]
