# Generated by Django 2.2.7 on 2019-11-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmanager', '0003_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='categorymanager.Category'),
        ),
    ]
